!pip install editdistance

In [1]:
%load_ext autoreload
%autoreload 2

import os
import datetime as dt

import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt

import torch
import torch.nn as nn

import models
import encoders
import decoders
from training import train, test, checkpoint, main_wandb, main_simple
from dataloaders import load_data, make_loaders, append_SOS


SEED = 27

np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed(SEED)
torch.backends.cudnn.deterministic = True

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

wandb: Currently logged in as: raraz15 (use `wandb login --relogin` to force relogin)


cuda


In [2]:
M = 8 

data_params = {'dataset_path': '/scratch/users/udemir15/ELEC491/bassline_transcription/data/datasets/[28, 51]',
               'dataset_name': 'TechHouse_bassline_representations',
               'scale_type': 'min',
               'M': M}

X, titles = load_data(data_params)
X = append_SOS(X)

K = X.max()+1 # Number of classes, assumes consecutive [0,max] inclusive
sequence_length = X.shape[1]

print('Number of classes: {}\nSequence Length: {}'.format(K, sequence_length))
print('Number of data points: {}'.format(X.shape[0]))

Number of classes: 27
Sequence Length: 65
Number of data points: 4421


X = X[:8]

frequencies = torch.tensor(np.unique(X, return_counts=True)).to(device)
cross_entropy_weights = frequencies[1].max() / frequencies[1]
cross_entropy_weights /= cross_entropy_weights.sum()
print('Cross entropy weights:\n{}\n'.format(cross_entropy_weights))
cross_entropy_weights = torch.FloatTensor(1 / (frequencies[1] / frequencies[1].max())).to(device)
print(cross_entropy_weights)

In [3]:
train_params = {'batch_size': 32,
               'N_epochs': 500,
               'teacher_forcing_ratio': 0.50,
               'lr': 1e-3}

encoder_params = {'input_size': K,
                  'embedding_size': 12,
                  'hidden_size': 128,
                  'n_layers': 2}

decoder_params = {'output_size': K,
                  'embedding_size': encoder_params['embedding_size'],
                  'hidden_size': encoder_params['hidden_size'],
                  'n_layers': encoder_params['n_layers']}

params = {'data_params': data_params,
          'encoder_params': encoder_params,
          'decoder_params':decoder_params, 
          'train_params':train_params}

encoder = encoders.Encoder(**encoder_params)
decoder = decoders.Decoder(**decoder_params)

model = models.Seq2Seq(encoder, decoder, device, train_params['teacher_forcing_ratio']).to(device)

print(model)
print('Number of parameters: {}'.format(sum([parameter.numel() for parameter in model.parameters()])))

criterion = nn.CrossEntropyLoss(reduction='mean')
optimizer = torch.optim.Adam(model.parameters(), lr=train_params['lr'])

train_loader, validation_loader, test_loader = make_loaders(X, train_params)

main_wandb(model, criterion, optimizer, device, train_loader, validation_loader, test_loader, params)
#main_simple(model, criterion, optimizer, device, train_loader, validation_loader, test_loader, params)

Seq2Seq(
  (encoder): Encoder(
    (embedding): Embedding(27, 12)
    (rnn): LSTM(12, 128, num_layers=2, batch_first=True)
  )
  (decoder): Decoder(
    (embedding): Embedding(27, 12)
    (rnn): LSTM(12, 128, num_layers=2, batch_first=True)
    (fc_out): Linear(in_features=128, out_features=27, bias=True)
  )
)
Number of parameters: 413731


  0%|          | 0/500 [00:00<?, ?it/s]


Before Training:
Test Loss: 3.2999, Test Accuracy: 0.0074, Test Distance: 63.48

Sample:
tensor([21, 21, 21,  4,  4,  4,  4, 18, 18, 18, 18, 18,  0, 18, 18, 18,  0, 23,
        18, 18,  0, 23, 18, 18,  0, 23, 18, 18,  0, 23, 18, 18,  0, 23, 18, 18,
         0, 23, 18, 18,  0, 23, 18, 18,  0, 23, 18, 18,  0, 23, 18, 18,  0, 23,
        18, 18,  0, 23, 18, 18,  0, 23, 18, 18], device='cuda:0')



  0%|          | 1/500 [00:10<1:23:56, 10.09s/it]

Epoch: 0, train_loss: 2.167648, train_acc: 0.400, val_loss: 2.031269, val_acc: 2.031
Sample:
tensor([26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
        26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
        26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
        26, 26, 26, 26, 26, 26, 26, 26, 26, 26], device='cuda:0')


  5%|▌         | 26/500 [03:50<1:07:47,  8.58s/it]

Epoch: 25, train_loss: 1.311433, train_acc: 0.555, val_loss: 1.324432, val_acc: 1.324


 10%|█         | 51/500 [07:33<1:04:12,  8.58s/it]

Epoch: 50, train_loss: 0.951473, train_acc: 0.673, val_loss: 1.068439, val_acc: 1.068
Sample:
tensor([10, 15, 26,  1,  1, 26,  1, 26, 26, 26, 26, 26,  1, 17,  1,  1, 19,  1,
         1,  1, 26,  1, 26, 26, 26, 26,  1,  1, 26, 26,  1, 26, 26, 26,  1,  1,
        26, 26, 26,  1, 26, 26, 26,  1, 26, 26,  1, 26, 26, 26,  1, 26, 26, 26,
         1, 26, 26, 26,  1, 26, 26, 26,  1, 26], device='cuda:0')


 15%|█▌        | 76/500 [11:11<1:02:16,  8.81s/it]

Epoch: 75, train_loss: 0.766994, train_acc: 0.738, val_loss: 1.092579, val_acc: 1.093


 20%|██        | 101/500 [14:51<57:32,  8.65s/it] 

Epoch: 100, train_loss: 0.646974, train_acc: 0.779, val_loss: 1.163570, val_acc: 1.164
Sample:
tensor([10, 10,  1,  3,  1, 26,  3,  1,  3,  1, 26, 26, 12, 26, 26, 26, 18, 26,
        26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,  1, 19, 26,
        26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
        26, 26, 19, 26, 26, 26, 26, 19, 26, 26], device='cuda:0')


 25%|██▌       | 126/500 [18:30<56:10,  9.01s/it]

Epoch: 125, train_loss: 0.560306, train_acc: 0.809, val_loss: 1.309920, val_acc: 1.310


 30%|███       | 151/500 [22:12<51:45,  8.90s/it]

Epoch: 150, train_loss: 0.471613, train_acc: 0.840, val_loss: 1.440838, val_acc: 1.441
Sample:
tensor([16,  1, 13,  1, 26, 26, 26, 13,  1, 10, 26,  1, 13,  1, 10,  1,  1, 15,
        15,  2, 26,  1, 26, 16, 26, 10, 26, 21, 26,  1, 26, 16, 26, 26, 26, 19,
        26, 19, 26, 22, 26, 19, 22, 26, 26,  1,  1, 19, 26, 26, 26,  9, 19, 19,
        26, 22, 26, 19, 26, 26, 26, 19,  1, 19], device='cuda:0')


 35%|███▌      | 176/500 [25:54<48:52,  9.05s/it]

Epoch: 175, train_loss: 0.421327, train_acc: 0.857, val_loss: 1.567691, val_acc: 1.568


 40%|████      | 201/500 [29:32<42:32,  8.54s/it]

Epoch: 200, train_loss: 0.350933, train_acc: 0.882, val_loss: 1.682319, val_acc: 1.682
Sample:
tensor([10, 25,  1, 20, 26,  1, 26, 26, 12, 11,  1, 15, 26,  1, 20,  1, 12,  1,
        15,  1, 22, 26, 26, 26, 26, 26, 26, 15, 26,  1, 26, 22, 26,  1, 26, 16,
        26, 26, 26, 22, 26,  1, 26, 16, 26, 26, 22, 26, 26, 26,  1, 19, 26, 22,
        26, 19, 26, 26,  1, 19, 26, 19, 26, 22], device='cuda:0')


 45%|████▌     | 226/500 [33:14<40:31,  8.87s/it]

Epoch: 225, train_loss: 0.288914, train_acc: 0.904, val_loss: 1.903110, val_acc: 1.903


 50%|█████     | 251/500 [36:54<36:45,  8.86s/it]

Epoch: 250, train_loss: 0.262577, train_acc: 0.913, val_loss: 2.080291, val_acc: 2.080
Sample:
tensor([20,  7,  1, 26, 10,  1, 17, 26,  1, 26, 13,  1, 16, 16,  1,  1,  7,  1,
        12, 26, 26, 17, 17, 26, 26,  1, 14, 26, 26,  1, 26,  7, 26, 26, 26, 26,
        26,  1, 17, 26, 26, 16, 26,  1, 19, 26, 22, 26, 26, 22, 26,  1, 19,  1,
        26, 19, 26, 26,  1, 19, 26,  1, 22, 26], device='cuda:0')


 55%|█████▍    | 273/500 [40:06<34:19,  9.07s/it]

KeyboardInterrupt: 

In [ ]:
test_loss, test_acc = test(model, test_loader, criterion, device)
samples = model.sample()

for epoch in tqdm(range(train_params['N_epochs'])):

    train_loss, train_acc = train(model, train_loader, optimizer, criterion, device)
    validation_loss, validation_acc = test(model, validation_loader, criterion, device)
    
    model.decoder.update_teacher_forcing_ratio(decoder_params['teacher_forcing_ratio']/train_params['N_epochs'])
    
    if epoch+1 % 5:
        print('Epoch: {}, train_loss: {:.6f}, acc: {:.3f}'.format(epoch+1, train_loss, train_acc))

test_loss, test_acc = test(model, test_loader, criterion, device)
print('Test Loss After Training: {:.6f}'.format(test_loss))