In [2]:
%load_ext autoreload

%autoreload 2

import os
import datetime as dt

import pandas as pd
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt

import torch
import torch.nn as nn

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

import models
import encoders
import decoders
from training import train, test, checkpoint
from dataloaders import load_data, create_loaders

WANDB_API_KEY= '52c84ab3f3b5c1f999c7f5f389f5e423f46fc04a'

import wandb
wandb.login() #key=WANDB_API_KEY

cuda


wandb: Currently logged in as: raraz15 (use `wandb login --relogin` to force relogin)


True

In [3]:
#dataset_path = '/projects/bassline_transcription/data/datasets'
dataset_path = '/scratch/users/udemir15/ELEC491/bassline_transcription/data/datasets'
dataset_name = 'traxsource_0-5000_bassline_representations'
M = 8 


data_params = {'dataset_path': dataset_path,
               'dataset_name': dataset_name,
               'scale_type': 'min',
               'M': M,
               'batch_size': 64}

X = load_data(data_params)

K = X.max()+1 # Number of classes, assumes consecutive
sequence_length = X.shape[1]

print('Number of classes: {}\nSequence Length: {}'.format(K, sequence_length))
print('Number of data points: {}'.format(X.shape[0]))

train_loader, test_loader = create_loaders(X, data_params)

Number of classes: 38
Sequence Length: 64
Number of data points: 3859


In [4]:
encoder_params = {'num_embeddings': K,
                  'embedding_dim': 16, 
                  'hidden_size': 128,
                  'dropout': 0.2,  
                  'num_layers': 4,              
                  'batch_size': data_params['batch_size'],
                  'device':device}

#StackedUnidirLSTMDenseDecoder / StackedUnidirectionalLSTMDecoder
decoder_params = {'input_size': encoder_params['hidden_size'],
                  'output_size': K,
                 'num_layers': encoder_params['num_layers'], 
                 'dropout': 0,
                 'batch_size': data_params['batch_size'],
                 'sequence_length': sequence_length,
                 'device':device}

#StackedUnidirectionalLSTMDecoderwithEmbedding 
"""decoder_params = {'num_embeddings': K,
                  'embedding_dim': 16,
                  'hidden_size': 128,                  
                  'num_layers': encoder_params['num_layers'], 
                  'dropout': 0.2,
                  'batch_size': data_params['batch_size'],
                  'sequence_length': sequence_length,
                  'device':device}"""

train_params = {'batch_size': data_params['batch_size'],
                'N_epochs': 500}

all_params = {'encoder_params': encoder_params, 'decoder_params':decoder_params, 'train_params':train_params}

encoder = encoders.StackedBidirLSTMEncoder(**encoder_params).to(device)

decoder = decoders.StackedUnidirLSTMDecoderwithEmbedding(**decoder_params).to(device)

model = models.AutoEncoder(encoder, decoder, device).to(device)
print(model)
print('Number of parameters: {}'.format(sum([parameter.numel() for parameter in model.parameters()])))

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [29]:
encoder = encoders.StackedBidirLSTMEncoder(**encoder_params).to(device)

#decoder = decoders.StackedUnidirLSTMDecoder(**decoder_params).to(device)
decoder = decoders.StackedUnidirLSTMDenseDecoder(**decoder_params).to(device)

model = models.VanillaAutoEncoder(encoder, decoder).to(device)
print(model)
print('Number of parameters: {}'.format(sum([parameter.numel() for parameter in model.parameters()])))

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

[autoreload of models failed: Traceback (most recent call last):
  File "/kuacc/apps/anaconda/3.6/envs/root_env/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/kuacc/apps/anaconda/3.6/envs/root_env/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 394, in superreload
    module = reload(module)
  File "/kuacc/apps/anaconda/3.6/envs/root_env/lib/python3.7/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/kuacc/apps/anaconda/3.6/envs/root_env/lib/python3.7/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, i

TypeError: __init__() got an unexpected keyword argument 'output_size'

In [28]:
if torch.rand(1) < 3:
    print('lol')

lol


In [10]:
project_name = 'PyTorch_experiments'

model_name = dt.datetime.strftime(dt.datetime.now(),"%d_%m__%H_%M")

with wandb.init(project=project_name, name=model_name, config=all_params, entity='nbg'):

    test_loss = test(model, test_loader, criterion, device)
    wandb.log({'test_loss': test_loss})

    for epoch in tqdm(range(train_params['N_epochs'])):

        train_loss = train(model, train_loader, optimizer, criterion, device)
        test_loss = test(model, test_loader, criterion, device)
        
        wandb.log({'train_loss': train_loss, 'test_loss': test_loss})

        if not (epoch % 5):
            print('Epoch: {}, train_loss:{:.6f}'.format(epoch, train_loss))
            checkpoint(model_name, model, optimizer, epoch)
            
        if not (epoch % 50):
            samples = model.sample(24)
            print('Sample: {}'.format(samples[0]))
            wandb.log({'samples': samples})

    test_loss = test(model, test_loader, criterion, device)
    print('Test Loss After Training: {:.6f}'.format(test_loss))
    wandb.log({'test_loss': test_loss})


  0%|          | 1/500 [00:06<57:02,  6.86s/it]

Epoch: 0, train_loss:2.258933
tensor([37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
        37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
        37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
        37, 37, 37, 37, 37, 37, 37, 37, 37, 37], device='cuda:0')



  1%|          | 6/500 [00:32<44:22,  5.39s/it]

Epoch: 5, train_loss:1.877414



  2%|▏         | 11/500 [01:01<47:25,  5.82s/it]

Epoch: 10, train_loss:1.809947



  3%|▎         | 16/500 [01:31<48:57,  6.07s/it]

Epoch: 15, train_loss:1.682607



  4%|▍         | 21/500 [02:03<50:02,  6.27s/it]

Epoch: 20, train_loss:1.665773



  5%|▌         | 26/500 [02:30<44:50,  5.68s/it]

Epoch: 25, train_loss:1.634993



  6%|▌         | 31/500 [03:00<46:22,  5.93s/it]

Epoch: 30, train_loss:1.738415



  7%|▋         | 36/500 [03:27<41:01,  5.31s/it]

Epoch: 35, train_loss:1.614046



  8%|▊         | 41/500 [03:55<41:36,  5.44s/it]

Epoch: 40, train_loss:1.532578



  9%|▉         | 46/500 [04:23<41:00,  5.42s/it]

Epoch: 45, train_loss:1.481188



 10%|█         | 51/500 [04:53<44:55,  6.00s/it]

Epoch: 50, train_loss:1.436909



 11%|█         | 56/500 [05:24<45:43,  6.18s/it]

Epoch: 55, train_loss:1.379475



 12%|█▏        | 61/500 [05:52<43:38,  5.97s/it]

Epoch: 60, train_loss:1.343186



 13%|█▎        | 66/500 [06:23<44:11,  6.11s/it]

Epoch: 65, train_loss:1.551306



 14%|█▍        | 71/500 [06:49<37:12,  5.20s/it]

Epoch: 70, train_loss:1.424802



 15%|█▌        | 76/500 [07:16<39:45,  5.63s/it]

Epoch: 75, train_loss:1.343666



 16%|█▌        | 81/500 [07:46<41:59,  6.01s/it]

Epoch: 80, train_loss:1.294069



 17%|█▋        | 86/500 [08:17<42:43,  6.19s/it]

Epoch: 85, train_loss:1.252446



 18%|█▊        | 91/500 [08:44<36:18,  5.33s/it]

Epoch: 90, train_loss:1.218312



 19%|█▉        | 96/500 [09:12<37:28,  5.57s/it]

Epoch: 95, train_loss:1.220128



 20%|██        | 101/500 [09:43<40:42,  6.12s/it]

Epoch: 100, train_loss:1.159520
tensor([ 1, 10, 12, 12, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
        37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
        37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,
        37, 37, 37, 37, 37, 37, 37, 37, 37, 37], device='cuda:0')



 21%|██        | 106/500 [10:13<38:29,  5.86s/it]

Epoch: 105, train_loss:1.128374



 22%|██▏       | 111/500 [10:43<39:25,  6.08s/it]

Epoch: 110, train_loss:1.123618



 23%|██▎       | 116/500 [11:13<36:09,  5.65s/it]

Epoch: 115, train_loss:1.162161



 24%|██▍       | 121/500 [11:39<33:03,  5.23s/it]

Epoch: 120, train_loss:1.061594



 25%|██▌       | 126/500 [12:06<33:04,  5.31s/it]

Epoch: 125, train_loss:1.111947



 26%|██▌       | 131/500 [12:38<38:10,  6.21s/it]

Epoch: 130, train_loss:1.047844



 27%|██▋       | 136/500 [13:10<38:41,  6.38s/it]

Epoch: 135, train_loss:1.024788



 28%|██▊       | 141/500 [13:41<37:31,  6.27s/it]

Epoch: 140, train_loss:1.025492



 29%|██▉       | 146/500 [14:11<36:28,  6.18s/it]

Epoch: 145, train_loss:0.977061



 30%|███       | 151/500 [14:39<31:29,  5.41s/it]

Epoch: 150, train_loss:1.170416



 31%|███       | 156/500 [15:10<34:53,  6.09s/it]

Epoch: 155, train_loss:1.052383



 32%|███▏      | 161/500 [15:41<35:32,  6.29s/it]

Epoch: 160, train_loss:1.226332



 33%|███▎      | 166/500 [16:12<34:29,  6.20s/it]

Epoch: 165, train_loss:1.057167



 34%|███▍      | 171/500 [16:41<30:10,  5.50s/it]

Epoch: 170, train_loss:1.004189



 35%|███▌      | 176/500 [17:06<28:39,  5.31s/it]

Epoch: 175, train_loss:0.947933



 36%|███▌      | 181/500 [17:34<28:07,  5.29s/it]

Epoch: 180, train_loss:0.918962



 37%|███▋      | 186/500 [18:05<31:25,  6.00s/it]

Epoch: 185, train_loss:0.905574



 38%|███▊      | 191/500 [18:29<26:04,  5.06s/it]

Epoch: 190, train_loss:0.861357



 39%|███▉      | 196/500 [18:53<25:19,  5.00s/it]

Epoch: 195, train_loss:0.860751



 40%|████      | 201/500 [19:18<24:14,  4.87s/it]

Epoch: 200, train_loss:0.826321
tensor([15, 37,  9, 10, 10, 10,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10], device='cuda:0')



 41%|████      | 206/500 [19:47<28:58,  5.91s/it]

Epoch: 205, train_loss:0.837914



 42%|████▏     | 211/500 [20:19<30:02,  6.24s/it]

Epoch: 210, train_loss:0.799917



 43%|████▎     | 216/500 [20:44<24:26,  5.16s/it]

Epoch: 215, train_loss:0.782893



 44%|████▍     | 221/500 [21:15<28:05,  6.04s/it]

Epoch: 220, train_loss:0.791547



 45%|████▌     | 226/500 [21:44<27:46,  6.08s/it]

Epoch: 225, train_loss:0.753611



 46%|████▌     | 231/500 [22:15<27:35,  6.15s/it]

Epoch: 230, train_loss:0.744405



 47%|████▋     | 236/500 [22:42<23:14,  5.28s/it]

Epoch: 235, train_loss:0.729638



 48%|████▊     | 241/500 [23:07<22:51,  5.30s/it]

Epoch: 240, train_loss:0.711241



 49%|████▉     | 246/500 [23:38<25:43,  6.08s/it]

Epoch: 245, train_loss:0.756116



 50%|█████     | 251/500 [24:09<25:06,  6.05s/it]

Epoch: 250, train_loss:0.685856



 51%|█████     | 256/500 [24:34<20:55,  5.15s/it]

Epoch: 255, train_loss:0.729207



 52%|█████▏    | 261/500 [25:01<20:40,  5.19s/it]

Epoch: 260, train_loss:0.656991



 53%|█████▎    | 266/500 [25:31<23:33,  6.04s/it]

Epoch: 265, train_loss:0.636072



 54%|█████▍    | 271/500 [26:02<24:03,  6.30s/it]

Epoch: 270, train_loss:0.632870



 55%|█████▌    | 276/500 [26:29<20:01,  5.36s/it]

Epoch: 275, train_loss:0.626174



 56%|█████▌    | 281/500 [26:53<17:55,  4.91s/it]

Epoch: 280, train_loss:0.656338



 57%|█████▋    | 286/500 [27:20<19:32,  5.48s/it]

Epoch: 285, train_loss:0.714500



 58%|█████▊    | 291/500 [27:45<17:53,  5.14s/it]

Epoch: 290, train_loss:0.628466



 59%|█████▉    | 296/500 [28:16<20:42,  6.09s/it]

Epoch: 295, train_loss:0.610211



 60%|██████    | 301/500 [28:46<19:29,  5.88s/it]

Epoch: 300, train_loss:0.580159
tensor([ 0, 17, 22, 30, 30, 30, 30, 30, 10, 10, 10, 10, 10, 10, 10, 37, 37, 37,
        37, 37, 37,  5, 37,  5,  5,  5,  5,  5,  5,  5, 37,  5, 37,  5,  5,  5,
         5,  5,  5,  5,  5,  5, 37,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5], device='cuda:0')



 61%|██████    | 306/500 [29:12<17:55,  5.54s/it]

Epoch: 305, train_loss:0.562631



 62%|██████▏   | 311/500 [29:44<19:32,  6.20s/it]

Epoch: 310, train_loss:0.693369



 63%|██████▎   | 316/500 [30:12<17:28,  5.70s/it]

Epoch: 315, train_loss:0.594596



 64%|██████▍   | 321/500 [30:38<16:28,  5.52s/it]

Epoch: 320, train_loss:0.558000



 65%|██████▌   | 326/500 [31:08<17:01,  5.87s/it]

Epoch: 325, train_loss:0.567351



 66%|██████▌   | 331/500 [31:35<15:18,  5.43s/it]

Epoch: 330, train_loss:0.536405



 67%|██████▋   | 336/500 [32:06<16:49,  6.15s/it]

Epoch: 335, train_loss:0.566527



 68%|██████▊   | 341/500 [32:38<16:59,  6.41s/it]

Epoch: 340, train_loss:0.488946



 69%|██████▉   | 346/500 [33:10<16:14,  6.33s/it]

Epoch: 345, train_loss:0.525290



 70%|███████   | 351/500 [33:41<15:40,  6.31s/it]

Epoch: 350, train_loss:0.507143



 71%|███████   | 356/500 [34:09<13:05,  5.45s/it]

Epoch: 355, train_loss:0.548166



 72%|███████▏  | 361/500 [34:38<13:33,  5.86s/it]

Epoch: 360, train_loss:0.485801



 73%|███████▎  | 366/500 [35:09<13:47,  6.18s/it]

Epoch: 365, train_loss:0.498095



 74%|███████▍  | 371/500 [35:37<11:43,  5.46s/it]

Epoch: 370, train_loss:0.540153



 75%|███████▌  | 376/500 [36:03<10:30,  5.08s/it]

Epoch: 375, train_loss:0.519621



 76%|███████▌  | 381/500 [36:30<11:02,  5.56s/it]

Epoch: 380, train_loss:0.492382



 77%|███████▋  | 386/500 [37:02<11:49,  6.23s/it]

Epoch: 385, train_loss:0.433402



 78%|███████▊  | 391/500 [37:33<11:28,  6.32s/it]

Epoch: 390, train_loss:0.424437



 79%|███████▉  | 396/500 [38:04<10:46,  6.21s/it]

Epoch: 395, train_loss:0.416901



 80%|████████  | 401/500 [38:32<09:19,  5.65s/it]

Epoch: 400, train_loss:0.386548
tensor([37, 37, 20, 14, 14, 12, 14, 13, 13, 13, 13, 13, 13, 12, 37, 14, 14, 14,
        14, 14, 14, 14, 14, 14, 14, 14, 14, 12, 14, 12, 37, 12, 37, 12, 37, 12,
        37, 12, 37, 12, 37, 12, 37, 12, 37, 12, 37, 12, 37, 12, 37, 12, 37, 12,
        37, 12, 37, 12, 37, 12, 37, 12, 37, 12], device='cuda:0')



 81%|████████  | 406/500 [39:03<09:42,  6.20s/it]

Epoch: 405, train_loss:0.395126



 82%|████████▏ | 411/500 [39:32<08:19,  5.61s/it]

Epoch: 410, train_loss:0.378296



 83%|████████▎ | 416/500 [40:02<07:57,  5.68s/it]

Epoch: 415, train_loss:0.456155



 84%|████████▍ | 421/500 [40:29<07:36,  5.78s/it]

Epoch: 420, train_loss:0.370157



 85%|████████▌ | 426/500 [40:57<07:12,  5.84s/it]

Epoch: 425, train_loss:0.331467



 86%|████████▌ | 431/500 [41:27<06:49,  5.94s/it]

Epoch: 430, train_loss:0.326805



 87%|████████▋ | 436/500 [41:58<06:39,  6.24s/it]

Epoch: 435, train_loss:0.324362



 88%|████████▊ | 441/500 [42:29<05:55,  6.03s/it]

Epoch: 440, train_loss:0.409444



 89%|████████▉ | 446/500 [43:00<05:37,  6.26s/it]

Epoch: 445, train_loss:0.318424



 90%|█████████ | 451/500 [43:29<04:49,  5.91s/it]

Epoch: 450, train_loss:0.292058



 91%|█████████ | 456/500 [43:57<04:20,  5.92s/it]

Epoch: 455, train_loss:0.284260



 92%|█████████▏| 461/500 [44:30<04:10,  6.42s/it]

Epoch: 460, train_loss:0.415511



 93%|█████████▎| 466/500 [44:58<03:18,  5.85s/it]

Epoch: 465, train_loss:0.300123



 94%|█████████▍| 471/500 [45:26<02:45,  5.70s/it]

Epoch: 470, train_loss:0.353705



 95%|█████████▌| 476/500 [45:51<02:02,  5.10s/it]

Epoch: 475, train_loss:0.336691



 96%|█████████▌| 481/500 [46:18<01:48,  5.69s/it]

Epoch: 480, train_loss:0.269882



 97%|█████████▋| 486/500 [46:50<01:26,  6.19s/it]

Epoch: 485, train_loss:0.271117



 98%|█████████▊| 491/500 [47:21<00:54,  6.10s/it]

Epoch: 490, train_loss:0.258189



 99%|█████████▉| 496/500 [47:48<00:22,  5.67s/it]

Epoch: 495, train_loss:0.259663



100%|██████████| 500/500 [48:12<00:00,  5.79s/it]


Test Loss After Training: 1.725295


In [ ]:
model.sample(24)[0]

test_loss = test(model, test_loader, criterion, device)

for epoch in tqdm(range(train_params['N_epochs'])):

    train_loss = train(model, train_loader, optimizer, criterion, device)
    
    if epoch+1 % 5:
        print('Epoch: {}, train_loss:{:.6f}'.format(epoch+1, train_loss))

test_loss = test(model, test_loader, criterion, device)
print('Test Loss After Training: {:.6f}'.format(test_loss))

encoder_params = {'num_embeddings': K,
                  'embedding_dim': 16, #??
                  'hidden_size': 128,
                  'dropout': 0,  
                  'num_layers': 4,              
                  'batch_size': data_params['batch_size'],
                  'device':device}

decoder_params = {'input_size': encoder_params['hidden_size'],
                  'output_size': K,
                 'num_layers': encoder_params['num_layers'], 
                 'dropout': 0,
                 'batch_size': data_params['batch_size'],
                 'sequence_length': sequence_length,
                 'device':device}

train_params = {'batch_size': data_params['batch_size'],
                'N_epochs': 10}

all_params = {'encoder_params': encoder_params, 'decoder_params':decoder_params, 'train_params':train_params}